name: Spring Boot Build Test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: "PANTS-GOORM/secrets"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: "external_files"

      - name: Set Secrets YML
        run: |
          mkdir -p src/main/resources
          cp application-properties-secrets.yml src/main/resources/application-properties-secrets.yml

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
