name: BACKEND CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v2

      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Extract version from merge commit message
        id: extract_version
        run: |
          VERSION=$(git log -1 --pretty=%B | grep -oP '(?<=v)\d+\.\d+\.\d+')
          if [[ ! -z "$VERSION" ]]; then
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          fi

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            yourusername/yourappname:latest
            yourusername/yourappname:${{ env.VERSION }}
        if: env.VERSION
